<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Nara.HardwareProfiler</AssemblyName>
    <RootNamespace>Nara.HardwareProfiler</RootNamespace>
    <Version>0.1.0</Version>
    <PublishTrimmed>false</PublishTrimmed>
    <NoWarn>$(NoWarn);SYSLIB1054</NoWarn>
  </PropertyGroup>
</Project>

